services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.vandenbrinksoftware.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    networks:
      - web

  portainer:
    labels:
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"

  sonarqube:
    labels:
      - "traefik.http.routers.sonarqube.tls=true"
      - "traefik.http.routers.sonarqube.tls.certresolver=myresolver"

  jenkins:
    user: root
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    command: >
      bash -c "apt-get update &&
               apt-get install -y curl gnupg2 software-properties-common &&
               curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - &&
               add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable' &&
               apt-get update &&
               apt-get install -y docker-ce-cli &&
               usermod -aG docker jenkins &&
               chown jenkins:docker /var/run/docker.sock &&
               su jenkins -c '/usr/local/bin/jenkins.sh'"
    labels:
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=myresolver"

networks:
  web:
    external: true
